####################
## Deployment values
####################
replicaCount: 1

containers:
  name: nss

metadata:
  name: nss-deployment

podLabels:
  app: nss
  app.kubernetes.io/version: nss

image:
  repository: oscarkowu/nss
  pullPolicy: IfNotPresent
  tag: "1410c12"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

livenessProbe:
  httpGet:
    path: /api/v1/health
    port: 8080
  initialDelaySeconds: 3
  periodSeconds: 3
  failureThreshold: 2

####################
## Service values
####################
service:
  metadata:
    name: nss-service
  selectors:
    app: nss
  type: LoadBalancer
  port: 3000
  targetPort: 8080
